### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by SqueezedLight** [wirecard/wpp-integration-demo-php#10]
Hello wirecard-team,
i recently implemented our new standalone wirecard payment page and had a rather bumpy experience. A lot of telephone calls (with Manfred Hölzl) were needed to make everything work. 
Some take-aways i wanna share:

- There is an unnecessary and very confusing `SECRET_KEY` [here](https://github.com/wirecard/wpp-integration-demo-php/blob/master/src/config.php#L5):.
This key is used in the demo code for signature verification. I have no idea why this works with the testing environment - in my opinion it shouldn't. But i can say that: it definitely doesn't work in production. For production one has to pass the appropriate `SECRET_KEY` for the current payment method. This is not possible with this demo code without some modifications. Would be nice if you could support this behaviour out-of-the-box. Of course this also effects other functions like `showValidSignature()` and so on...

- I suffered from some naming inconsistencies. `getPaymentMethod()` returns `creditcard` for a credit card payment. Due to the first point above, one already needs a server-side logic to get the appropriate secret for a specific payment method. The demo code uses `ccard` to identify credit card payments. But the wpp backend returns `creditcard`. Harmonized naming of all payment methods would make life easier. Like using the same naming conventions across the entire demo code and make sure to be compatible with the responses of wirecard payment end-points (use either `ccard` OR `creditcard` in the demo code AND in the responses).

- Certificate-pinning seems to be optional. I would rather comment the code [here](https://github.com/wirecard/wpp-integration-demo-php/blob/master/src/util/helperFunctions.php#L126) and write a notice where to get a certificate in case someone would like to use it. Currently for me the code suggest mandatory certificate-pinning.
BTW: The credentials we got from wirecard didn't contain any certificate.

- Would be much nicer if all those secret definitions in [helperFunctions.php](https://github.com/wirecard/wpp-integration-demo-php/blob/master/src/util/helperFunctions.php) would be in [config.php](https://github.com/wirecard/wpp-integration-demo-php/blob/master/src/config.php). Also the `helperFunctions.php` contains a hard-coded `BASE_URL` which is already defined in `config.php`.

- The configuration for 3D & NON 3D is not clear. The [comment](https://github.com/wirecard/wpp-integration-demo-php/blob/master/src/util/helperFunctions.php#L132) seems to be incomplete. 
The demo code sets both, 3D&NON3D. But as far as i understand it, you either send a 3D request OR an NON3D request. Not both? So why set both credentials here? A comment better comment would be nice.

- Last but not least - the most irritating thing: Please document all your end-points. I wasted hours because i didn't know that the correct end-point was not `wpp.wirecard.com` but `wpp-wdcee.wirecard.com`. Our merchant infos (which we got from our wirecard support guy) only reflects the base url, but not the wpp url. It is bad enough that there are so many different endpoint, but not documenting anything makes it a nightmare.

Hope this helps to improve things a bit. Please let me know if any of my assumptions are incorrect.

Happy hacking and cheers from Graz ;)

**Comment by horfic** [comment]
Hi SqueezedLight,
thank you for this valuable feedback.

Some of the mentioned points are already planned to be resolved, others are already resolved.

cheers,
Your wirecard team

**Comment by quiret** [comment]
It would be great if you guys sent the new WPPv2 credentials to new customers instead of the old api.wirecard.com details only. I take it that an ee user is not equal to the access that is required to "wpp-wdcee.wirecard.com"? Calling technical support by phone is, like, impossible. Hoping for a quick resolution! My case is pretty related to OP's because the documentation is not great.

**Comment by avalarh** [comment]
A half year has passed since this issue had been created and the documentation issue is not resolved yet.

**Comment by JanSlabon** [comment]
The documentation and the demos are written from a person knowing the internals but not from a users perspective. Awful...

**Comment by mke-wd** [comment]
Hi!

Thanks for the reminder. I'm sorry that this issue has not yet been resolved properly.

We will have an in detail look at it and see where we can improve.

BR
Your Wirecard Team.
