### ISSUE TITLE
Explicit require file missing: autoload.php

### ISSUE THREAD

**Issue by maythilr** [wirecard/wpp-integration-demo-php#20]
Hi, Can you please add the following file into this repo please? Not able to get the demos working without. Thanks, Ravi

Line 108  of below file:
requires '../../vendor/autoload.php' (currently missing)

Ref:
https://github.com/wirecard/wpp-integration-demo-php/blob/master/src/payment/seamless.php

**Comment by jakubpolomsky** [comment]
Hello @maythilr,

the autoload.php file gets automatically generated when you execute the `composer install` command. If you wish to omit the development dependencies (e.g. code quality tools) you can use the command `composer install --no-dev`

Kind regards,
Team Wirecard

**Comment by maythilr** [comment]
Thank you for your response.

Downloaded & extracted the wpp-integration-demo-php-master.zip. Tried installing via command "composer install --no-dev" as suggested. Encountered this error. Stuck (Screenshot attached).

![Screen Shot 2019-06-18 at 6 15 22 pm](https://user-images.githubusercontent.com/51673974/59674335-ac956e00-91f5-11e9-883e-e53b11abd99b.png)


Just looking for a simple php integration code that works in seamless mode.

**Comment by maythilr** [comment]
... this is the directory listing of the working directory.

![Screen Shot 2019-06-18 at 6 21 45 pm](https://user-images.githubusercontent.com/51673974/59674518-05fd9d00-91f6-11e9-8a0e-d25bcae5ac8d.png)

**Comment by jakubpolomsky** [comment]
Please enable the intl php extension as the error message states. You can do it in the `/etc/php/7.2/cli/php.ini` file by uncommenting the `extension=php_intl.so` line. For the web the php.ini file will be located elsewhere. Meaning there will be two locations where you need to enable it. After that re-run the composer command and you will be ready to go in no time.

**Comment by maythilr** [comment]
Thank you so much. Enabling the .ini file alone did not help (the actual line was ;extension=intl)

Had to do this: 
sudo apt-get install php7.0-intl

After this re-run composer worked and all good now.

Quick check? In our eventual live/production environment we will need this extension installed if we are using parts of this done. Only interested in seamless integration.

**Comment by jakubpolomsky** [comment]
You really need the intl for the seamless part. That is the only way how we can reliably determine the locale of the users browser.

**Comment by maythilr** [comment]
Hi Jakub, we are having difficulties with our integration for seamless mode. Noticed that there now example requests for seamless but only for standalone/embedded. We have used the standalone example json (wpp-integration-demo-php/example-requests-standalone/creditcard_payment_3DS.json) instead.

When we use the demo merchant account id & currency all works well. But when we replace these values with our UAT merchant account id or currency, it fails with errors as described in attachment.

[wc-integration-issues-seamless.pptx](https://github.com/wirecard/wpp-integration-demo-php/files/3324616/wc-integration-issues-seamless.pptx)

**Comment by maythilr** [comment]
Hi, Please advice if this needs to be re-directed to another team pls advice. thx in advance.
