### ISSUE TITLE
SEPA signature validation is not working

### ISSUE THREAD

**Issue by cbou** [wirecard/wpp-integration-demo-php#22]
Signature validation is working for credit card but not for SEPA direct debit.

Does the SEPA direct debit need different secret key than "a8c3fce6-8df7-4fd6-a1fd-62fa229c5e55" ?

**Comment by mke-wd** [comment]
Hi!

Sorry for the late response! 

That could be the problem you're facing. 

You can take a look at the possible config values for test merchants inside the:
https://github.com/wirecard/paymentSDK-php/blob/master/examples/configuration/globalconfig.php

Let me know, whether this solves your problem, otherwise we will invesitage further!

BR
Moritz

**Comment by cbou** [comment]
Hi Moritz, server key "ecdf5990-0372-47cd-a55d-037dccfe9d25" is not working too.

**Comment by mke-wd** [comment]
Hi!

Can you just quickly outline your workflow steps, so I can have a look at it? 

Thank you!

**Comment by cbou** [comment]
1. Clone the repository
2. Run `composer install`
3. Change a few configuration https://github.com/cbou/wpp-integration-demo-php/commit/6375c540002098948a0efcbf9142c094fc59dd33
4. Go to http://wirecard-test/src/register/standalone_overview.html
5. Select Credit card or SEPA
6. Use the credit card details from https://github.com/wirecard/wpp-integration-demo-php
7. Then I valid the payment and scroll down to validSignature it should show True

![Screenshot 2019-07-12 at 12 49 35](https://user-images.githubusercontent.com/611389/61123014-8afd6e80-a4a3-11e9-90e4-ccd82dc94287.png)

With credit card the validation returns true when I change the secret key from "a8c3fce6-8df7-4fd6-a1fd-62fa229c5e55" to "dbc5a498-9a66-43b9-bf1d-a618dd399684".

For SEPA I can't find the correct configuration to use.

I would expect this repository to be pre-configured out of the box with the right credentials.

**Comment by mke-wd** [comment]
Hi!

I'm sorry for the  inconveniences. There have been some changes in the merchant configurations. Please use the secret '5caf2ed9-5f79-4e65-98cb-0b70d6f569aa' for SEPA.

Unfortunately this one won't work for Credit Card. 

BR 
Moritz

**Comment by cbou** [comment]
Thanks moritz.

The new secret worked for me.

**Comment by cbou** [comment]
Just a quick question.

Is that ok to use this secret in CI like travis or jenkins to do end-to-end tests that go through the checkout? We want to make sure our Wirecard integration is working.

**Comment by mke-wd** [comment]
Hi! 

Basically there are no limitation how to use the credentials, therefore you can use them for testing purposes.
If you have received the credentials for production, you also can use them for testing, but please consider that they will be cleared from our side (they will be included within the month bill)

Please also make sure that your secret key is not publically visible! 

BR
Moritz

**Comment by cbou** [comment]
Thanks
