### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by masitings** [wirecard/wpp-integration-demo-php#23]
Hi i got this error when i attempt to pay : 

> Error getting response from Tokenization (remote) Server

are this was kind of server point issues ? are there's something wrong with my code ?

**Comment by mke-wd** [comment]
Hi!

Can you pleace specifiy where you get the error, at which point of the workflow? And which integration type (Embedded, Hosted or Seamless) you are using? 

Thank you !

BR
Moritz

**Comment by MarkusHobisch** [comment]
Hi!

Could you reproduce the error? Have you still troubles with tokenization?

BR
Markus
