### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by varioous** [wirecard/wpp-integration-demo-php#50]
Should be compatible with php Version 7.4.*
`
  Problem 1
    - Installation request for wirecard/payment-sdk-php 4.0.0 -> satisfiable by wirecard/payment-sdk-php[4.0.0].
    - wirecard/payment-sdk-php 4.0.0 requires php 5.6.* || 7.0.* || 7.1.* || 7.2.* || 7.3.* -> your PHP version (7.4.2) does not satisfy that requirement.
`

**Comment by ubkpesek** [comment]
Could we get some information regarding update to PHP 7.4? Is it even planned?

**Comment by MarkusHobisch** [comment]
In general it should be also compatible with PHP 7.4 but we did not test it so far. As this project depends on payment_sdk_php we wait until it is updated to php 7.4.The pull request is already open, you can see it here: https://github.com/wirecard/paymentSDK-php/pull/683. Sorry that I cannot give you a more precise answer.
