### ISSUE TITLE
Correspondent form

### ISSUE THREAD

**Issue by jtheim** [wirecard/wpp-integration-demo-php#7]
Hi all! Could anybody provide an example of a corresponding html/php form? I do not understand how to feed the *.json file with the data.
Thanks in advance
cheers

**Comment by horfic** [comment]
Hi jtheim,
sorry for the late responds.

Please have a look at documentation of the appropiate payment method you are trying out to get a better understanding of the json.

https://document-center.wirecard.com/display/PTD/Payment+Methods+with+WPP

cheers
